FROM ubuntu:24.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y git build-essential curl libclang-dev

ENV PATH=/root/.cargo/bin:$PATH

ADD rust-toolchain /code/redbx/rust-toolchain

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain=$(cat /code/redbx/rust-toolchain)

ADD . /code/redbx/

RUN cd /code/redbx && cargo bench --no-run -p redbx-bench
